# -*- coding: utf-8 -*-
"""AI Website Cloner Agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jx0CFNFKqz7nhajOuwlA2yAOqOdDf8QU
"""

!pip install requests beautifulsoup4 groq lxml

!pip install groq

!pip install html2image

!pip install nest_asyncio pyngrok

"""GROQ Setup"""

client = Groq(
    api_key="GROQ_API_KEY"
)

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role":"user",
            "content":"Say Hello"
        }
    ]
)

print(
    response.choices[0].message.content
)

"""Website Scraper"""

import requests
from bs4 import BeautifulSoup

def scrape_website(url):

    headers = {
        "User-Agent": "Mozilla/5.0"
    }

    response = requests.get(
        url,
        headers=headers,
        timeout=20
    )

    soup = BeautifulSoup(
        response.text,
        "html.parser"
    )

    title = (
        soup.title.text.strip()
        if soup.title
        else ""
    )

    headings = [
        h.get_text(strip=True)
        for h in soup.find_all(
            ["h1","h2","h3"]
        )
    ]

    paragraphs = [
        p.get_text(strip=True)
        for p in soup.find_all("p")
    ]

    links = [
        a.get_text(strip=True)
        for a in soup.find_all("a")
        if a.get_text(strip=True)
    ]

    buttons = [
        b.get_text(strip=True)
        for b in soup.find_all("button")
    ]

    return {
        "title": title,
        "headings": headings[:30],
        "paragraphs": paragraphs[:30],
        "links": links[:30],
        "buttons": buttons[:20]
    }

"""Testing"""

data = scrape_website(
    "https://stripe.com"
)

print(data)

def create_layout_json(data):

    prompt = f"""
Analyze website data.

Website:

{data}

Return JSON:

{{
  "navbar": [],
  "hero_heading": "",
  "hero_subheading": "",
  "cta_buttons": [],
  "sections": [],
  "footer": ""
}}

Return JSON only.
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ]
    )

    return (
        response
        .choices[0]
        .message
        .content
    )

"""Website Analyzer"""

def analyze_website(data):

    prompt = f"""
Analyze website data.

Website:

{data}

Return JSON:

{{
 "website_type":"",
 "navbar":[],
 "hero_heading":"",
 "hero_subheading":"",
 "sections":[],
 "cta":"",
 "target_audience":""
}}

Return JSON only.
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ]
    )

    return (
        response
        .choices[0]
        .message
        .content
    )

analysis = analyze_website(data)

print(analysis)

"""Clone Generator"""

def generate_clone_from_layout(layout):

    prompt = f"""
Create a complete responsive website.

Layout:

{layout}

Requirements:

1. Tailwind CSS CDN
2. Responsive
3. Modern SaaS UI
4. Professional navbar
5. Hero section
6. CTA buttons
7. Features section
8. Footer

Return ONLY HTML.
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ],
        temperature=0.2
    )

    return (
        response
        .choices[0]
        .message
        .content
    )

layout = create_layout_json(
    data
)

html_code = generate_clone_from_layout(
    layout
)

"""Save Clone"""

with open(
    "generated_clone.html",
    "w",
    encoding="utf-8"
) as f:

    f.write(html_code)

print(
    "Clone saved"
)

def website_cloner(url):

    print("Scraping Website...")

    data = scrape_website(url)

    print("Creating Layout...")

    layout = create_layout_json(
        data
    )

    print("Generating Clone...")

    html_code = (
        generate_clone_from_layout(
            layout
        )
    )

    with open(
        "generated_clone.html",
        "w",
        encoding="utf-8"
    ) as f:

        f.write(html_code)

    return html_code

print(layout)

from IPython.display import HTML

clone = website_cloner(
    "https://stripe.com"
)

HTML(clone)

"""Fast API"""

from fastapi import FastAPI, Form

import nest_asyncio
nest_asyncio.apply()

from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def home():
    return {
        "message":"AI Website Cloner Running"
    }

import uvicorn
import threading

def run_server():
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000
    )

thread = threading.Thread(
    target=run_server
)

thread.start()

@app.post("/clone")
def clone(url: str = Form(...)):

    html = website_cloner(url)

    return HTMLResponse(html)

import nest_asyncio
nest_asyncio.apply()

import requests

print(
    requests.get(
        "http://127.0.0.1:8000"
    ).text
)

ngrok.set_auth_token(
    "NGROK_API_KEY"
)